### PR TITLE
Fix for variants

### PR DESCRIPTION
**Pull request by costashatz**
Fix for #48 ...

### CODE REVIEW

**Comment by costashatz** [comment]
@JoostHuizinga when you try it and it works, let me know to merge...

**Comment by JoostHuizinga** [comment]
Works!

**Comment by JoostHuizinga** [comment]
Minor comment, when compiling, it is no longer clear which variant is being build. For example, when I build my maze experiment with three variants, the compiling phase looks like this:

```
[12/47] Compiling exp/cmoea/maze.cpp
[13/47] Compiling exp/cmoea/maze.cpp
[14/47] Compiling exp/cmoea/maze.cpp
```

Though the linking phase shows which variants those were.

```
[45/47] Linking build/exp/cmoea/maze_dbg_jhdebug_nsga_gen20_pop20
[46/47] Linking build/exp/cmoea/maze_dbg_jhdebug_cmoea_gen20_pop20_div
[47/47] Linking build/exp/cmoea/maze_dbg_jhdebug_nsga_gen20_pop20_div
```

That said, I am really glad the variants feature no longer creates a separate cpp files for each variant. That got messy really quickly.

**Comment by costashatz** [comment]
> Minor comment, when compiling, it is no longer clear which variant is being build.

Yes this is true, but I haven't really checked how I can display that. In addition, I never really found a reason I would want exactly to see what is compiling. And since it can be seen when linking I think it is not a big issue. So I am **merging**...

**Pull request merged**
