### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by costashatz**
This PR aims to fix travis.. It is not to be **merged** yet..

### CODE REVIEW

**Comment by jbmouret** [comment]
does it work?

**Comment by costashatz** [comment]
> does it work?

I am trying to make it work.. I think I am close..

**Comment by costashatz** [comment]
Seems to work.. Now we need to actually get the output of the tests.. Or do we already?

**Comment by costashatz** [comment]
Now it works but sometimes some of the tests fail. @jbmouret why are some tests failing? Not always, but sometimes..

**Comment by jbmouret** [comment]
Some tests are stochastic are might fail sometimes (e.g. trying an
evolutionary algorithm). We should probably run these algorithms  a few
times before declaring that the test fails.

**Comment by costashatz** [comment]
> Some tests are stochastic are might fail sometimes (e.g. trying an
> evolutionary algorithm). We should probably run these algorithms  a few
> times before declaring that the test fails.

Do you remember which of them are stochastic? So, I can edit the code and they are run more than once..

**Comment by jbmouret** [comment]
I would say that the ones that can fail are:
    /home/travis/build/sferes2/sferes2/build/tests/tests_ea_cmaes
    /home/travis/build/sferes2/sferes2/build/tests/tests_ea_nsga2
  /home/travis/build/sferes2/sferes2/build/tests/tests_ea_eps_moea

but I wrote them years ago!...

**Comment by costashatz** [comment]
@jbmouret I tried many things.. There's some weird errors with gcc (no matter what version) and boost unit test (no matter what version)... Anyway, we have something now that should not fail to often, but fail when something important is broken..

**Comment by costashatz** [comment]
@jbmouret should we merge this? It's better than nothing...

**Comment by jbmouret** [comment]
Yes, OK.

**Pull request merged**
