### PR TITLE
Fixes for #45

### PR DESCRIPTION
**Pull request by costashatz**
Fixes for #45~~, **WIP**~~:

- ~~Fix for TBB~~
- ~~Output include and libs found when verbose~~

**EDIT**:  Added Lmod as in #52...

### CODE REVIEW

**Comment by costashatz** [comment]
@JoostHuizinga I added verbose output to all includes/libs that sferes searches (I think) and I made an updated copy of your implementation for lmod autodetect (as in #52). Can you check that it works so that we can merge? Thanks!

**Comment by JoostHuizinga** [comment]
I have tested it on Mount Moran, and it doesn't work. The problem is that, for Intel's impi (which is the version installed on Mount Moran), libmpi_cxx.so does not exist. Instead, they have libmpicxx.so. However, if the test is ignored, Sferes is properly build, because the mpicxx wrapper compiler adds the correct libraries automatically.

I can see two ways of handling this issue. First, we could check whether we are building with impi, and look for the mpicxx library, rather than mpi_cxx library, if that is the case (the most useful environment variable to check for would be LMOD_FAMILY_MPI=impi). 

Alternatively, we could check whether our compiler is an mpi wrapper compiler (e.g. CXX=mpicxx), and not check for mpi libraries at all when the compiler is set to mpicxx. The promise of these wrapper compilers is that they know which libraries to link, and where these libraries are.

**Comment by costashatz** [comment]
> First, we could check whether we are building with impi, and look for the mpicxx library, rather than mpi_cxx library, if that is the case (the most useful environment variable to check for would be LMOD_FAMILY_MPI=impi).

I think there is an easier way to solve. I am pushing a quick fix for you to check if it's working.. Thanks..

**Comment by costashatz** [comment]
@JoostHuizinga let me know if it works..

**Comment by JoostHuizinga** [comment]
That worked! Also, sorry for being slow, I'm a bit new to the more advanced features of git.

**Pull request merged**
